/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customers;

import javax.swing.JOptionPane;

/**
 *
 * @author LAPTOP
 */
public class Complain extends javax.swing.JFrame {
    CustomerSource r= new CustomerSource();
    private boolean isnumric(String num){
        if(num==null)
            return false;
         try{
             int i=Integer.parseInt(num);
         }catch(NumberFormatException ee){return false;}
         return true;
    }
    /**
     * Creates new form Complain
     */
    public Complain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit_meterCode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        edit_complain = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        edit_complainField = new javax.swing.JTextField();
        btn_submitComplain = new javax.swing.JButton();
        edit_meterCode1 = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        edit_meterCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_meterCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        edit_meterCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_meterCodeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        edit_complain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Meter code");

        edit_complainField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        edit_complainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_complainFieldActionPerformed(evt);
            }
        });

        btn_submitComplain.setBackground(new java.awt.Color(0, 153, 153));
        btn_submitComplain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_submitComplain.setForeground(new java.awt.Color(255, 255, 255));
        btn_submitComplain.setText("Submit");
        btn_submitComplain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_submitComplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitComplainActionPerformed(evt);
            }
        });

        edit_meterCode1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_meterCode1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        edit_meterCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_meterCode1ActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 153, 153));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_complainLayout = new javax.swing.GroupLayout(edit_complain);
        edit_complain.setLayout(edit_complainLayout);
        edit_complainLayout.setHorizontalGroup(
            edit_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_complainLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btn_submitComplain, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(edit_complainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edit_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_complainLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(edit_meterCode1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(edit_complainField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_complainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        edit_complainLayout.setVerticalGroup(
            edit_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_complainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(edit_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_meterCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(edit_complainField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_submitComplain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_complain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_complain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_meterCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_meterCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_meterCodeActionPerformed

    private void edit_complainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_complainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_complainFieldActionPerformed

    private void btn_submitComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitComplainActionPerformed
        // TODO add your handling code here:
        if(isnumric(edit_meterCode1.getText())){
        if(!edit_meterCode1.getText().isEmpty()&& !edit_complainField.getText().isEmpty())
        {
            
                int meterCode= Integer.parseInt(edit_meterCode1.getText());
                String complain= edit_complainField.getText();
                int id=r.Add_complain(meterCode, (java.time.LocalDate.now()).toString(), complain, r.getBill_date(meterCode));
                JOptionPane.showMessageDialog(null, "Thanks for dealing with us\nYour Complain ID: "+id);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter the meter code and the complain",
                null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_submitComplainActionPerformed

    private void edit_meterCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_meterCode1ActionPerformed
        // TODO add your handling code here:
        //        gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_edit_meterCode1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
//        this.toBack();
//        setVisible(true);
//        new OldCustomer().toFront();
//        new OldCustomer().setState(java.awt.Frame.NORMAL);
OldCustomer e=new OldCustomer ();
        e.setVisible(true);
        
        this.setVisible(false);
//        
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submitComplain;
    private javax.swing.JPanel edit_complain;
    private javax.swing.JTextField edit_complainField;
    private javax.swing.JTextField edit_meterCode;
    private javax.swing.JTextField edit_meterCode1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
