/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customers;

import javax.swing.JOptionPane;

/**
 *
 * @author LAPTOP
 */
public class OldCustomer extends javax.swing.JFrame {
    CustomerSource r= new CustomerSource();
    /**
     * Creates new form OldCustomer
     */
    private boolean isnumric(String num){
        if(num==null)
            return false;
         try{
             int i=Integer.parseInt(num);
         }catch(NumberFormatException ee){return false;}
         return true;
    }
    public OldCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edit_fname3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        edit_meterCode = new javax.swing.JTextField();
        btn_pay = new javax.swing.JButton();
        btn_complain = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edit_bill = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_submit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        edit_fname3.setBackground(new java.awt.Color(255, 255, 255));
        edit_fname3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Meter code");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        edit_meterCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_meterCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        edit_meterCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_meterCodeActionPerformed(evt);
            }
        });

        btn_pay.setBackground(new java.awt.Color(0, 153, 153));
        btn_pay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pay.setForeground(new java.awt.Color(255, 255, 255));
        btn_pay.setText("Pay");
        btn_pay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });

        btn_complain.setBackground(new java.awt.Color(0, 153, 153));
        btn_complain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_complain.setForeground(new java.awt.Color(255, 255, 255));
        btn_complain.setText("Complain");
        btn_complain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_complainActionPerformed(evt);
            }
        });

        edit_bill.setColumns(20);
        edit_bill.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        edit_bill.setRows(5);
        edit_bill.setEditable(false);
        edit_bill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        String text="*****Enter MeterCode Up There*****";
        edit_bill.setText(text);
        jScrollPane1.setViewportView(edit_bill);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill");
        jLabel1.setToolTipText("");

        btn_submit.setBackground(new java.awt.Color(0, 153, 153));
        btn_submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Submit");
        btn_submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 153, 153));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_submit1.setBackground(new java.awt.Color(0, 153, 153));
        btn_submit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_submit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit1.setText("AddMeterReading");
        btn_submit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        btn_submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_fname3Layout = new javax.swing.GroupLayout(edit_fname3);
        edit_fname3.setLayout(edit_fname3Layout);
        edit_fname3Layout.setHorizontalGroup(
            edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_fname3Layout.createSequentialGroup()
                .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_fname3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edit_fname3Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(edit_meterCode))
                            .addGroup(edit_fname3Layout.createSequentialGroup()
                                .addComponent(btn_submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_fname3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_complain, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(edit_fname3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        edit_fname3Layout.setVerticalGroup(
            edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_fname3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_meterCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_submit)
                    .addComponent(btn_submit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edit_fname3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_fname3Layout.createSequentialGroup()
                        .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_complain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_fname3Layout.createSequentialGroup()
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_fname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_fname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_meterCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_meterCodeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_edit_meterCodeActionPerformed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        // TODO add your handling code here:

        //Check if the form filled
        if(!edit_meterCode.getText().isEmpty() )
        {
            if(isnumric(edit_meterCode.getText())){
                int  meterCode= Integer.parseInt(edit_meterCode.getText());
                r.update("bill", "paid", "1", "bill_date='"+r.getBill_date(meterCode)+"' and meter_code="+meterCode);
            JOptionPane.showMessageDialog(null, "Thanks for dealing with us");
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter the meter code in digits",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter the meter code",
                null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_payActionPerformed

    private void btn_complainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_complainActionPerformed
        // TODO add your handling code here:
        Complain comp=new Complain();
        comp.show();
        dispose();
//        this.toBack();
//        Complain newframe= new Complain();
//        newframe.setVisible(true);
//        newframe.toFront();
    }//GEN-LAST:event_btn_complainActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        
        if(isnumric(edit_meterCode.getText())){
            if(!edit_meterCode.getText().isEmpty())
            {
                int  meterCode= Integer.parseInt(edit_meterCode.getText());
                int total_bill=r.getBill(meterCode);
                int unpaid=r.NumberUnpaidMonths(meterCode);
                if(total_bill==-999){
                    edit_bill.setText("Your bills have been paid\nThere's no bills for you.");
                }
                else{
                        if(unpaid>=3)
                        edit_bill.setText("Your recent bill: "+total_bill+" EGP\nyou have "+unpaid+" upaid unpaid bills\npaid Bills: "+r.NumberPaidMonths(meterCode)+"\nplease contact us on 256486 to \npay the bills or\nyour subscription will be stopped");
                        else
                            edit_bill.setText("recent Bill: "+total_bill+"\nyou have "+unpaid+" upaid unpaid bills\npaid Bills: "+r.NumberPaidMonths(meterCode)+"");
                        }
            }
        }
        else {
              
            JOptionPane.showMessageDialog(null,"Enter Data(MeterCode)",
                null, JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        //        this.toBack();
        //        setVisible(true);
        //        new OldCustomer().toFront();
        //        new OldCustomer().setState(java.awt.Frame.NORMAL);
        customer_services e=new customer_services ();
        e.setVisible(true);

        this.setVisible(false);
        //
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit1ActionPerformed
        // TODO add your handling code here:
        if(!edit_meterCode.getText().isEmpty()){
            new MeterReadingInsertion(Integer.parseInt(edit_meterCode.getText())).setVisible(true);
            this.setVisible(false);}
        else{
            JOptionPane.showMessageDialog(null,"Enter Data(MeterCode)",
                null, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_submit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_complain;
    private javax.swing.JButton btn_pay;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_submit1;
    private javax.swing.JTextArea edit_bill;
    private javax.swing.JPanel edit_fname3;
    private javax.swing.JTextField edit_meterCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private int Int(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
