/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpage;

import customers.AdminSource;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public class EditP extends javax.swing.JFrame {
    AdminSource r =new AdminSource();
    /**
     * Creates new form EditP
     */
    public EditP() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        edt_username = new javax.swing.JTextField();
        edt_password = new javax.swing.JTextField();
        edt_email = new javax.swing.JTextField();
        edt_region = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_region = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_delete = new javax.swing.JButton();
        edt_id_delete = new javax.swing.JTextField();
        lbl_id_delete = new javax.swing.JLabel();
        lbl_meter_code_delete = new javax.swing.JLabel();
        edt_meter_code_delete = new javax.swing.JTextField();
        Delete_title = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        lbl_id_update = new javax.swing.JLabel();
        lbl_meter_code_update = new javax.swing.JLabel();
        lbl_column = new javax.swing.JLabel();
        lbl_value = new javax.swing.JLabel();
        edt_id_update = new javax.swing.JTextField();
        edt_meter_code_update = new javax.swing.JTextField();
        edt_column = new javax.swing.JTextField();
        edt_value = new javax.swing.JTextField();
        Add_title = new javax.swing.JLabel();
        types = new javax.swing.JComboBox<>();
        Update_title = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit");

        jPanel4.setBackground(new java.awt.Color(151, 119, 151));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        lbl_username.setText("Username");

        lbl_region.setText("Region");

        lbl_password.setText("Password");

        lbl_email.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_add))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lbl_region, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(edt_region, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(edt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_region))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(99, 95, 156));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        lbl_id_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id_delete.setForeground(new java.awt.Color(204, 204, 204));
        lbl_id_delete.setText("ID");

        lbl_meter_code_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_meter_code_delete.setForeground(new java.awt.Color(204, 204, 204));
        lbl_meter_code_delete.setText("MeterCode");

        Delete_title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete_title.setText("Delete");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_delete))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_meter_code_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_id_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_meter_code_delete)
                            .addComponent(edt_id_delete))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Delete_title, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(Delete_title)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_delete)
                    .addComponent(edt_id_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_meter_code_delete)
                    .addComponent(edt_meter_code_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btn_delete)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(193, 139, 130));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        lbl_id_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id_update.setText("ID");

        lbl_meter_code_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_meter_code_update.setText("MeterCode");

        lbl_column.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_column.setText("Column");

        lbl_value.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_value.setText("Value");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_column, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_meter_code_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_id_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_id_update)
                            .addComponent(edt_meter_code_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(edt_column, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(edt_value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_update)
                            .addComponent(edt_id_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_meter_code_update))
                    .addComponent(edt_meter_code_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_column)
                    .addComponent(edt_column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_value)
                    .addComponent(edt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addContainerGap())
        );

        Add_title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Add_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_title.setText("ADD");

        types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Admin", "Operator" }));
        types.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typesActionPerformed(evt);
            }
        });

        Update_title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Update_title.setText("Update");

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_title, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Update_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back))
                .addGap(18, 18, 18)
                .addComponent(types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Update_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new AdminPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void typesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typesActionPerformed
        edt_id_delete.setVisible(true);
        edt_id_update.setVisible(true);
        lbl_id_delete.setVisible(true);
        lbl_id_update.setVisible(true);
        edt_username.setVisible(true);
        edt_password.setVisible(true);
        lbl_password.setVisible(true);
        lbl_username.setVisible(true);
        edt_meter_code_delete.setVisible(true);
        lbl_meter_code_delete.setVisible(true);
        lbl_region.setVisible(true);
        edt_region.setVisible(true);
        edt_email.setVisible(true);
        lbl_email.setVisible(true);
        lbl_id_update.setVisible(true);
        edt_id_update.setVisible(true);
        lbl_meter_code_update.setVisible(true);
            edt_meter_code_update.setVisible(true);
        if(types.getSelectedItem()=="Customer"){
            edt_id_delete.setVisible(false);
            edt_id_update.setVisible(false);
            lbl_id_delete.setVisible(false);
            lbl_id_update.setVisible(false);
            edt_username.setVisible(false);
            edt_password.setVisible(false);
            lbl_password.setVisible(false);
            lbl_username.setVisible(false);
        }
        else if(types.getSelectedItem()=="Operator"){
            edt_meter_code_delete.setVisible(false);
            lbl_meter_code_delete.setVisible(false);
            lbl_region.setVisible(false);
            edt_region.setVisible(false);
            edt_email.setVisible(false);
            lbl_email.setVisible(false);
            lbl_meter_code_update.setVisible(false);
            edt_meter_code_update.setVisible(false);
            edt_id_delete.setSize(200,150);
        }
        else if(types.getSelectedItem()=="Admin"){
            edt_meter_code_delete.setVisible(false);
            lbl_meter_code_delete.setVisible(false);
            lbl_region.setVisible(false);
            edt_region.setVisible(false);
            edt_email.setVisible(false);
            lbl_email.setVisible(false);
            lbl_meter_code_update.setVisible(false);
            edt_meter_code_update.setVisible(false);
            edt_id_delete.setSize(200,150);
        }
    }//GEN-LAST:event_typesActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(types.getSelectedItem()=="Customer"){
            if(!edt_email.getText().isEmpty()&&!edt_region.getText().isEmpty()){
                r.insert_old_customer(edt_region.getText(), edt_email.getText());
                JOptionPane.showMessageDialog(this,"his/her MeterCode: "+r.get_meter_code());
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Email/Region)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Operator"){
            if(!edt_username.getText().isEmpty()&&!edt_password.getText().isEmpty()){
                int id=r.insert_user(edt_username.getText(), edt_password.getText(), "operator");
                JOptionPane.showMessageDialog(this,"his/her ID: "+id);
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Username/Password)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Admin"){
            if(!edt_username.getText().isEmpty()&&!edt_password.getText().isEmpty()){
                int id=r.insert_user(edt_username.getText(), edt_password.getText(), "admin");
                JOptionPane.showMessageDialog(this,"his/her ID: "+id);
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Username/Password)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if(types.getSelectedItem()=="Customer"){
            if(!edt_meter_code_delete.getText().isEmpty()){
                r.Delete("old_customer", "meter_code="+edt_meter_code_delete.getText());
                JOptionPane.showMessageDialog(this,"Customer with MeterCode: "+edt_meter_code_delete.getText()+" Deleted");
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Delete->MeterCode)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Operator"){
            if(!edt_id_delete.getText().isEmpty()){
                r.Delete("employee", "id="+edt_id_delete.getText());
                JOptionPane.showMessageDialog(this,"User with ID: "+edt_id_delete.getText()+" Deleted");
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Delete->ID)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Admin"){
            if(!edt_id_delete.getText().isEmpty()){
                r.Delete("employee", "id= "+edt_id_delete.getText());
                JOptionPane.showMessageDialog(this,"User with ID: "+edt_id_delete.getText()+" Deleted");
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Delete->ID)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(types.getSelectedItem()=="Customer"){
            if(!edt_column.getText().isEmpty() && !edt_value.getText().isEmpty() && (!edt_meter_code_update.getText().isEmpty())){
                r.update_customer(Integer.parseInt(edt_meter_code_update.getText()), edt_column.getText(), edt_value.getText(), "1");
                JOptionPane.showMessageDialog(this,"Customer with MeterCode: "+edt_id_delete.getText()+" his/her "+edt_column.getText()+" updated to "+edt_value.getText());
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Update->(MeterCode,Column,Value))",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Operator"){
            if(!edt_column.getText().isEmpty() && !edt_value.getText().isEmpty() && (!edt_id_update.getText().isEmpty())){
                r.update_for_user(Integer.parseInt(edt_id_update.getText()), edt_column.getText(), edt_value.getText());
                JOptionPane.showMessageDialog(this,"User with ID: "+edt_id_delete.getText()+" his/her "+edt_column.getText()+" updated to "+edt_value.getText());
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Update->(ID,Column,Value))",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(types.getSelectedItem()=="Admin"){
            if(!edt_column.getText().isEmpty() && !edt_value.getText().isEmpty() && (!edt_id_update.getText().isEmpty())){
                r.update_for_user(Integer.parseInt(edt_id_update.getText()), edt_column.getText(), edt_value.getText());
                JOptionPane.showMessageDialog(this,"User with ID: "+edt_id_delete.getText()+" his/her "+edt_column.getText()+" updated to "+edt_value.getText());
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Data(Update->(ID,Column,Value))",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_title;
    private javax.swing.JLabel Delete_title;
    private javax.swing.JLabel Update_title;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField edt_column;
    private javax.swing.JTextField edt_email;
    private javax.swing.JTextField edt_id_delete;
    private javax.swing.JTextField edt_id_update;
    private javax.swing.JTextField edt_meter_code_delete;
    private javax.swing.JTextField edt_meter_code_update;
    private javax.swing.JTextField edt_password;
    private javax.swing.JTextField edt_region;
    private javax.swing.JTextField edt_username;
    private javax.swing.JTextField edt_value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_column;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id_delete;
    private javax.swing.JLabel lbl_id_update;
    private javax.swing.JLabel lbl_meter_code_delete;
    private javax.swing.JLabel lbl_meter_code_update;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_region;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_value;
    private javax.swing.JComboBox<String> types;
    // End of variables declaration//GEN-END:variables
}
