/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpage;


import customers.CollectedPayments;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public class operator extends javax.swing.JFrame {
    OperatorSource r=new OperatorSource();
    String region;
    /**
     * Creates new form operator
     */
    public operator() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setLocation(500,250);
        this.setTitle("Operator");
        initComponents();
        tariff_lbl.setVisible(false);
        edt_s_tariff.setVisible(false);
        region_lbl.setVisible(false);
        edt_region.setVisible(false);
        t_area.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        functions = new javax.swing.JComboBox<>();
        MC_lbl = new javax.swing.JLabel();
        edt_meter_code = new javax.swing.JTextField();
        edt_s_tariff = new javax.swing.JTextField();
        tariff_lbl = new javax.swing.JLabel();
        region_lbl = new javax.swing.JLabel();
        edt_region = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OperatorView");

        functions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CollectPayments", "PrintBill", "ValidateReading", "StopSubscription", "SetTariff", "RegionBills" }));
        functions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionsActionPerformed(evt);
            }
        });

        MC_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MC_lbl.setForeground(new java.awt.Color(204, 204, 204));
        MC_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MC_lbl.setText("MeterCode");

        tariff_lbl.setForeground(new java.awt.Color(204, 204, 204));
        tariff_lbl.setText("Tariff");

        region_lbl.setForeground(new java.awt.Color(204, 204, 204));
        region_lbl.setText("Region");

        //t_area.setText;
        t_area.setColumns(20);
        t_area.setEditable(false);
        t_area.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_area.setRows(5);
        jScrollPane1.setViewportView(t_area);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(MC_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_meter_code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tariff_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edt_s_tariff, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(region_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edt_region, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(functions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(71, 71, 71))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(MC_lbl)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_meter_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_s_tariff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tariff_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(region_lbl)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void functionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionsActionPerformed
        // TODO add your handling code here:
        MC_lbl.setVisible(true);
        edt_meter_code.setVisible(true);
        if(functions.getSelectedItem().toString()=="SetTariff"){
           tariff_lbl.setVisible(true);
           edt_s_tariff.setVisible(true);
           region_lbl.setVisible(false);
           edt_region.setVisible(false);
           
        }
        else if(functions.getSelectedItem().toString()=="RegionBills"){
            region_lbl.setVisible(true);
            edt_region.setVisible(true);
            edt_meter_code.setVisible(false);
            MC_lbl.setVisible(false);
            tariff_lbl.setVisible(false);
            edt_s_tariff.setVisible(false);
        }
        else{
            if(functions.getSelectedItem().toString()=="CollectPayments"){
                t_area.setVisible(true);
            }
            else if(functions.getSelectedItem().toString()=="PrintBill"){t_area.setVisible(true);}
            else if(functions.getSelectedItem().toString()=="ValidateReading"){t_area.setVisible(false);}
            else{
                t_area.setVisible(false);
            }
            tariff_lbl.setVisible(false);
            edt_s_tariff.setVisible(false);
            region_lbl.setVisible(false);
            edt_region.setVisible(false);
            
        }
    }//GEN-LAST:event_functionsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(functions.getSelectedItem().toString()=="CollectPayments"){
            
            if(!edt_meter_code.getText().isEmpty()){
                int meter_code=Integer.parseInt(edt_meter_code.getText());
                new CollectedPayments(meter_code).setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(null, "Enter Date(Meter_code)",
                null, JOptionPane.ERROR_MESSAGE);
        }
        else if(functions.getSelectedItem().toString()=="PrintBill"){
            String Bill="testing_bills";
            if(!edt_meter_code.getText().isEmpty()){
                int meter_code=Integer.parseInt(edt_meter_code.getText());
                int bill=r.getBill(meter_code);
                if(bill!=-999){
                    t_area.setText("Meter_code: "+meter_code+"\nTotal_Bill "+bill);
                }
                else t_area.setText("Meter_code: "+meter_code+"\nTotal_Bill "+0);
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter Date(Meter_code)",
                null, JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(functions.getSelectedItem().toString()=="ValidateReading"){
            String Bill="testing_Reading";
            if(!edt_meter_code.getText().isEmpty()){
                int meter_code=Integer.parseInt(edt_meter_code.getText());
                new ReadingValidation(meter_code).setVisible(true);
                this.setVisible(false);
            }
            else{
            JOptionPane.showMessageDialog(null, "Enter Date(Meter_code)",
                null, JOptionPane.ERROR_MESSAGE);}
        }
        /*CollectPayments, PrintBill, ValidateReading, StopSubscription, SetTariff, RegionBills*/
        else if(functions.getSelectedItem().toString()=="StopSubscription"){
            if(!edt_meter_code.getText().isEmpty())
            {
                int meter_code=Integer.parseInt(edt_meter_code.getText());
                r.update_customer(meter_code, "subscription", "0", "1");
                JOptionPane.showMessageDialog(null, "stopped");
            }
            else
                JOptionPane.showMessageDialog(null, "Enter Date(Meter_code)",
                null, JOptionPane.ERROR_MESSAGE);
        }
        else if(functions.getSelectedItem().toString()=="SetTariff"){
            if(!edt_s_tariff.getText().isEmpty()&& !edt_meter_code.getText().isEmpty()){
                int meter_code=Integer.parseInt(edt_meter_code.getText());
                r.update_customer(meter_code, "tariff", edt_s_tariff.getText(), "1");
                JOptionPane.showMessageDialog(null, "setted");}
            else
                JOptionPane.showMessageDialog(null, "Enter Date(Meter_code,Tariff)",
                null, JOptionPane.ERROR_MESSAGE);
        }
        
        else if(functions.getSelectedItem().toString()=="RegionBills"){
            if(!edt_region.getText().isEmpty()){
                region=edt_region.getText();
                new RegionBills(region).setVisible(true);
                
                this.setVisible(false);
                }
            else
                JOptionPane.showMessageDialog(null, "Enter Date(Region)",
                null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginPage l=new LoginPage();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MC_lbl;
    private javax.swing.JTextField edt_meter_code;
    public static javax.swing.JTextField edt_region;
    private javax.swing.JTextField edt_s_tariff;
    private javax.swing.JComboBox<String> functions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel region_lbl;
    private javax.swing.JTextArea t_area;
    private javax.swing.JLabel tariff_lbl;
    // End of variables declaration//GEN-END:variables
}
